Repository robyngoodner/React, pull requests merged in 2022-03, with the labels that each got.

#17 Register component
  client/src/components/Register/index.jsx
  server/routes/users.js
Labels: documentation

#26 register mods
  server/controllers/auth.js
  server/controllers/index.js
  server/models/user.js
Labels: help wanted

#29 Show Event
  client/src/api/event.service.js
  client/src/components/Event/EventView.js
  server/controllers/event.js
  server/routes/event.js
Labels: enhancement
